server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    # 网关配置
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh1 #payment_route 路由ID，没有固定规则但必须唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb:http://cloud-payment-service #动态路由
          predicates: #
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
            - After=2021-12-29T22:47:39.381+08:00[Asia/Shanghai] # 符合地区-时间之后访问才放行
            - Before=2022-11-29T22:47:39.381+08:00[Asia/Shanghai] # 符合地区-时间之前访问才放行
            - Between=2021-12-29T22:47:39.381+08:00[Asia/Shanghai],2022-11-29T22:47:39.381+08:00[Asia/Shanghai] #时间之间访问
#            - Cookie=username,test #带Cookie访问
#            - Header=X-Request-Id,123 #带Header访问
#            - Host=xxx #带Host访问
#            - Query=xxx,xx #参数
#            - Method=GET #请求类型

        - id: payment_routh2 #payment_route 路由ID，没有固定规则但必须唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb:http://cloud-payment-service #动态路由
          predicates:
            - Path=/payment/discovery  #断言，路径相匹配的进行路由
            - After=2021-12-29T22:47:39.381+08:00[Asia/Shanghai] # 符合地区-时间之后访问才放行

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka #单机版
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka  #集群版  #集群版
  instance:
    prefer-ip-address: true # 开启使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #ip:port