server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    # 网关配置
    gateway:
      routes:
        - id: payment_routh1 #payment_route 路由ID，没有固定规则但必须唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route 路由ID，没有固定规则但必须唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/discovery  #断言，路径相匹配的进行路由

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka #单机版
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka  #集群版  #集群版
  instance:
    prefer-ip-address: true # 开启使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #ip:port