server:
  port: 7001

#eureka配置
eureka:
  instance:
    hostname: eurekaStandAlone #eureka服务端的实例名称
    prefer-ip-address: true # 开启使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #ip:port
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒，默认30s
    lease-renewal-interval-in-seconds: 10
    # Eureka服务端在收到最后一次心跳后等待时间上限，单位是秒，默认90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 10
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，职责就是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/