server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于与binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: 106.55.199.12 #localhost
                port: 5672
                username: admin
                password: admin
      bindings:  #服务的整合处理
        output: #
          destination: studyExchange  #表示要使用的Exchange名称定义
          content-type: application/json #设置消息类型 文本为text/plain
          binder: defaultRabbit #设置

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true  #访问路径可以显示IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #实例名称 ip:port